### PR TITLE
make opencv fetch content-able

### PR DESCRIPTION
**Pull request by mehermvr**
Opencv can be fetch content-ed as #6 tried to do.
HBST has a `#include <opencv2/opencv.hpp>` which needs the `OpenCV_INCLUDE_DIRS` to be set manually.
I've disabled a lot of stuff when building opencv, that probably needs a check.

### CODE REVIEW

**Review by saurabh1002 — APPROVED** [review]
LGTM thanks very much @mehermvr

**Comment by saurabh1002** [comment]
@mehermvr could you also remove the dependency from the README

**Comment by mehermvr** [comment]
> @mehermvr could you also remove the dependency from the README

updated it. also indicated that eigen too is optional

**Review by tizianoGuadagnino — APPROVED** [review]
Thanks everybody including @l00p3

**Pull request merged**
